#!/usr/bin/env python3
import os
import sys
from argparse import ArgumentParser, FileType
from pathlib import Path
from subprocess import run, PIPE


def main():
    parser = ArgumentParser()

    parser.add_argument('--recursive', action='store_true')
    parser.add_argument('--count', action='store_true')

    parser.add_argument('--installed', action='store_true')
    parser.add_argument('--available', action='store_true')
    parser.add_argument('--missing', action='store_true')

    parser.add_argument('paths', metavar='FILE', nargs='+', type=Path)

    args = parser.parse_args()

    for path in args.paths:
        if not path.exists():
            print(f'{path} does not exist', file=sys.stderr)


if __name__ == '__main__':
    main()
